apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
  compileSdkVersion 33
  defaultConfig {
    applicationId "com.example.calculator"
    minSdkVersion 21
    targetSdkVersion 33
    versionCode 1
    versionName "1.0"
  }
  buildTypes {
    release {
      minifyEnabled true
      shrinkResources true
    }
  }
}

dependencies {
  implementation 'androidx.core:core:1.9.0'
  implementation 'androidx.appcompat:appcompat:1.6.1'
  implementation 'com.google.android.material:material:1.8.0'
}