targets:
  $default:
    builders:
      # Custom build rules configuration if needed
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint_error
            - invalid_annotation_target
